### ISSUE TITLE
Adding a release with a binary

### ISSUE THREAD

**Issue by fatso83** [neosmart/paste#2]
Would you mind creating a release along with a built binary? I know it's not a lot that's needed to build this, but it's basically a simple util that people wants, not the experience of setting up a cli build chain on Windows 😄 

While _I know_ how to download the msbuild.exe I would rather not ... and I think most others are in the same boat, so to speak :)

**Comment by fatso83** [comment]
For latecomers, if you want a way of dumping the clipboard, just use win32yank, which has prebuilt binaries. Here's how to set it up to work just as the macOS `pbpaste` command:
```
alias pbpaste='win32yank.exe -o'
```

Closing this, as I am not really interested anymore.

**Comment by mqudsi** [comment]
Hello,

Sorry this took some time, but I wanted to polish a point release before publishing a binary. I've just uploaded `paste.exe` [to the 2.0 release](https://github.com/neosmart/paste/releases/tag/2.0), the new features that I wanted to get done before publishing the binary are listed there (including a new icon).

The binary is authenticode signed and will work for all x86 and x64 hosts from Windows XP onwards.
